/** Site-wide legal entity & support contact (footer, emails, legal pages, API). */

export const LEGAL_COMPANY_NAME = 'ESD Media LLC';

export const SUPPORT_EMAIL = 'supportstratum@gmail.com';
export const SUPPORT_MAILTO = `mailto:${SUPPORT_EMAIL}`;

/** Opens the user's mail app with a pre-filled support message (no server SMTP). */
export function buildFeedbackMailto({ name, email, message }) {
  const subject = `[STRATUM.ai] Feedback from ${String(name ?? '').trim().slice(0, 120)}`;
  const body = [
    `Name: ${String(name ?? '').trim()}`,
    `Email: ${String(email ?? '').trim()}`,
    '',
    String(message ?? '').trim(),
  ].join('\n');
  const params = new URLSearchParams();
  params.set('subject', subject);
  params.set('body', body.slice(0, 6000));
  return `${SUPPORT_MAILTO}?${params.toString()}`;
}
export const SUPPORT_PHONE = '(307) 295-0454';
export const SUPPORT_PHONE_TEL = `tel:${SUPPORT_PHONE.replace(/\D/g, '')}`;
export const CONTACT_SUPPORT_LABEL = 'Contact support';

/** Telegram channel — daily IELTS tips & quizzes */
export const TELEGRAM_CHANNEL_URL = 'https://t.me/+yb4-_ZjVPUgwOWIy';
export const TELEGRAM_CHANNEL_LABEL = 'Join us on Telegram';

/** Telegram bot — DM essay check & commands */
export const TELEGRAM_BOT_USERNAME = 'Stratum_ielts_writing_bot';
export const TELEGRAM_BOT_URL = `https://t.me/${TELEGRAM_BOT_USERNAME}?start=check`;
export const TELEGRAM_BOT_LABEL = 'STRATUM IELTS Writing Bot';

/** Facebook page — STRATUM.ai community */
export const FACEBOOK_PAGE_URL = 'https://www.facebook.com/share/1DU54kSfUs/';
export const FACEBOOK_PAGE_LABEL = 'Follow us on Facebook';

/** Instagram profile — STRATUM.ai */
export const INSTAGRAM_PAGE_URL = 'https://www.instagram.com/stratum573?igsh=MXJrZzZ5Y2JkaXMweA==';
export const INSTAGRAM_PAGE_LABEL = 'Follow us on Instagram';

export const REGISTERED_AGENT_NAME = 'ESD Media LLC';
export const REGISTERED_AGENT_ADDRESS = '30 N Gould St Ste N, Sheridan, WY 82801, USA';

export const MAILING_ADDRESS = '30 N Gould St Ste N, Sheridan, WY 82801, USA';
export const PRINCIPAL_OFFICE_ADDRESS = MAILING_ADDRESS;

/** Public-facing business / correspondence address (principal office). */
export const BUSINESS_ADDRESS = PRINCIPAL_OFFICE_ADDRESS;

export const COPYRIGHT_LINE = `© 2026 ${LEGAL_COMPANY_NAME}. Registered in Wyoming, USA. All rights reserved. ${BUSINESS_ADDRESS}`;

export const COPYRIGHT_SHORT = `© 2026 ${LEGAL_COMPANY_NAME}. Registered in Wyoming, USA.`;

export const EMAIL_LEGAL_FOOTER = `${LEGAL_COMPANY_NAME}, ${BUSINESS_ADDRESS}`;

export const PDF_BRAND_TAGLINE = 'Generated by STRATUM.ai — Your Roadmap to Band 9.0';
export const PDF_LEGAL_LINE = `${LEGAL_COMPANY_NAME} · ${BUSINESS_ADDRESS}`;
export const PDF_CONTACT_LINE = `${CONTACT_SUPPORT_LABEL}: ${SUPPORT_EMAIL}`;
