"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { useSession } from 'next-auth/react';
import { useTheme } from '@wrksz/themes/client';
import { useRouter } from 'next/navigation';
import { mergeLexicalUpgrades, getWeakWordsSet } from '@/lib/lexicalUpgrade';
import { DEFAULT_PROMPT_T1_ACADEMIC } from '@/lib/writer/constants';
import { DEFAULT_LETTER_META } from '@/lib/task1LetterPrompt';
import { useSuggestedRewriteAudio } from '@/components/dashboard/useSuggestedRewriteAudio';
import { generateStratumWritingPdf } from '@/lib/lazyStratumPdf';
import { getEssayWordCount, scrollToEditor } from '@/lib/writer/editorUi';
import { useAnalyze } from '@/hooks/useAnalyze';
import { useWriterStorageKeys } from '@/hooks/writer/useWriterStorageKeys';
import { useWriterNavRestore } from '@/hooks/writer/useWriterNavRestore';
import { useWriterPersistence } from '@/hooks/writer/useWriterPersistence';
import { useWriterArchive } from '@/hooks/writer/useWriterArchive';
import { useWriterTaskGeneration } from '@/hooks/writer/useWriterTaskGeneration';
import { useWriterEditorTools } from '@/hooks/writer/useWriterEditorTools';
import { useWriterShare } from '@/hooks/writer/useWriterShare';
import { useWriterScrollUi } from '@/hooks/writer/useWriterScrollUi';
import { useWriterFeedback } from '@/hooks/writer/useWriterFeedback';
import { useWriterTimer } from '@/hooks/writer/useWriterTimer';
import { useWriterManualScoring } from '@/hooks/writer/useWriterManualScoring';
import { preloadSpeechVoices, speakText } from '@/lib/speakText';
import { trackGoogleAdsPurchaseConversion } from '@/lib/googleAdsConversions';

export function useWriterWorkspace({
  forceLandingFromServer = false,
  skipAppLandingFromServer = false,
} = {}) {
  const [essayT2, setEssayT2] = useState('');
  const [isAutoGenerated, setIsAutoGenerated] = useState(false);
  const [activeTab, setActiveTab] = useState('Home');
  const [currentTopic, setCurrentTopic] = useState(null);
  const [essayT1, setEssayT1] = useState('');
  const [appliedCorrections, setAppliedCorrections] = useState([]);
  const [customKeyword, setCustomKeyword] = useState('');
  const [isPromptOpen, setIsPromptOpen] = useState(true);
  const [credits, setCredits] = useState(0);
  const [image, setImage] = useState(null);
  const [isImageCollapsed, setIsImageCollapsed] = useState(false);
  const [loadingT1, setLoadingT1] = useState(false);
  const [loadingT2, setLoadingT2] = useState(false);
  const [promptT1Academic, setPromptT1Academic] = useState(DEFAULT_PROMPT_T1_ACADEMIC);
  const [promptT1Letter, setPromptT1Letter] = useState('');
  const [promptT2, setPromptT2] = useState('');
  const [task1Kind, setTask1Kind] = useState('academic');
  const promptT1Active = task1Kind === 'gt_letter' ? promptT1Letter : promptT1Academic;
  const [letterMeta, setLetterMeta] = useState(() => ({ ...DEFAULT_LETTER_META }));
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const activeResultsRef = useRef(null);
  const scrollToScoreAfterAnalyzeRef = useRef(false);
  const [activeResultT1, setResultT1] = useState(null);
  const [error, setError] = useState(null);
  const [errorIs401, setErrorIs401] = useState(false);
  const [activeResultT2, setResultT2] = useState(null);
  const [tutorCommentT1, setTutorCommentT1] = useState('');
  const [tutorCommentT2, setTutorCommentT2] = useState('');
  const [isAuthOpen, setIsAuthOpen] = useState(false);
  const [authModalMessage, setAuthModalMessage] = useState(null);
  const [isLoggedIn, setIsLoggedIn] = useState(false);
  const [isFocused, setIsFocused] = useState(false);

  const { resolvedTheme } = useTheme();
  const [themeMounted, setThemeMounted] = useState(false);
  useEffect(() => {
    setThemeMounted(true);
  }, []);
  const darkMode = themeMounted && resolvedTheme === 'dark';

  const activeResult = activeTab === 'Task 1' ? activeResultT1 : activeResultT2;
  const activeAnalyzeLoading = activeTab === 'Task 1' ? loadingT1 : loadingT2;
  const isGtLetter = activeTab === 'Task 1' && task1Kind === 'gt_letter';

  const mergedLexicalUpgrade = useMemo(() => {
    const lexSource = activeTab === 'Task 1' ? activeResultT1 : activeResultT2;
    const essay = activeTab === 'Task 1' ? essayT1 : essayT2;
    return mergeLexicalUpgrades({
      apiRows: Array.isArray(lexSource?.lexical_upgrade) ? lexSource.lexical_upgrade : [],
      essayText: essay || '',
      isT1: activeTab === 'Task 1',
    });
  }, [activeTab, activeResultT1, activeResultT2, essayT1, essayT2]);

  const weakWordsSet = useMemo(() => getWeakWordsSet(mergedLexicalUpgrade), [mergedLexicalUpgrade]);

  const { data: session, status: sessionStatus, update } = useSession();
  const creditsFetchedForAuthRef = useRef(false);
  const creditsTopUpDismissedRef = useRef(false);
  const [creditsSynced, setCreditsSynced] = useState(false);
  const [showCreditsTopUpModal, setShowCreditsTopUpModal] = useState(false);

  const openCreditsTopUpModal = () => {
    creditsTopUpDismissedRef.current = false;
    setShowCreditsTopUpModal(true);
  };

  const closeCreditsTopUpModal = () => {
    creditsTopUpDismissedRef.current = true;
    setShowCreditsTopUpModal(false);
  };
  const router = useRouter();
  const { workspaceStorageKey, draftStorageKey, archiveStorageKey } = useWriterStorageKeys(session);

  const { forceLanding, skipAppLanding } = useWriterNavRestore({
    forceLandingFromServer,
    skipAppLandingFromServer,
    setActiveTab,
    setTask1Kind,
    setPromptT1Letter,
    setPromptT1Academic,
    setLetterMeta,
    setImage,
    setEssayT1,
    setEssayT2,
  });

  useWriterPersistence({
    workspaceStorageKey,
    draftStorageKey,
    setEssayT1,
    setEssayT2,
    setPromptT1Academic,
    setPromptT1Letter,
    setPromptT2,
    setActiveTab,
    setImage,
    setTask1Kind,
    setLetterMeta,
    setResultT1,
    setResultT2,
    setTutorCommentT1,
    setTutorCommentT2,
    setCurrentTopic,
    setIsAutoGenerated,
    setIsImageCollapsed,
    essayT1,
    essayT2,
    activeTab,
    promptT1Academic,
    promptT1Letter,
    promptT2,
    image,
    task1Kind,
    letterMeta,
    activeResultT1,
    activeResultT2,
    tutorCommentT1,
    tutorCommentT2,
    currentTopic,
    isAutoGenerated,
    isImageCollapsed,
  });

  const taskGen = useWriterTaskGeneration({
    customKeyword,
    setPromptT2,
    setCurrentTopic,
    setIsAutoGenerated,
    setActiveTab,
    setTask1Kind,
    setPromptT1Academic,
    setPromptT1Letter,
    setImage,
    setAuthModalMessage,
    setIsAuthOpen,
    setError,
    setErrorIs401,
  });

  const archiveApi = useWriterArchive({
    archiveStorageKey,
    session,
    sessionStatus,
    activeTab,
    essayT1,
    essayT2,
    promptT1Active,
    promptT2,
    activeResultT1,
    activeResultT2,
    tutorCommentT1,
    tutorCommentT2,
    setTutorCommentT1,
    setTutorCommentT2,
    image,
    setEssayT1,
    setEssayT2,
    setResultT1,
    setResultT2,
    setPromptT1Academic,
    setPromptT1Letter,
    setPromptT2,
    setTask1Kind,
    setImage,
    setActiveTab,
  });

  const isSaved =
    activeTab === 'Task 1' ? archiveApi.archiveSavedT1 : activeTab === 'Task 2' ? archiveApi.archiveSavedT2 : false;

  const editorTools = useWriterEditorTools({
    activeTab,
    essayT1,
    essayT2,
    setEssayT1,
    setEssayT2,
    activeResult,
    darkMode,
    mergedLexicalUpgrade,
    weakWordsSet,
    setAppliedCorrections,
  });

  const manualScoring = useWriterManualScoring({
    activeTab,
    essayT1,
    essayT2,
    activeResultT1,
    activeResultT2,
    tutorCommentT1,
    tutorCommentT2,
    setResultT1,
    setResultT2,
  });

  const shareApi = useWriterShare({
    session,
    activeResult,
    activeResultT1,
    activeResultT2,
    setIsAuthOpen,
    syncBeforeShare: manualScoring.syncBothTasksIfNeeded,
  });

  const scrollUi = useWriterScrollUi();
  const feedbackApi = useWriterFeedback();
  const timer = useWriterTimer(activeTab);

  const karaokeSuggestedRewrite =
    activeTab === 'Task 1' || activeTab === 'Task 2' ? activeResult?.suggested_rewrite || '' : '';
  const karaokeFilenameBase = activeTab === 'Task 1' ? 'Stratum_Task1_Rewrite' : 'Stratum_Task2_Rewrite';
  const karaokeAudio = useSuggestedRewriteAudio(karaokeSuggestedRewrite, karaokeFilenameBase);

  useEffect(() => {
    if (sessionStatus === 'authenticated' && session?.user) {
      setIsLoggedIn(true);
      // Seed from JWT only before the first /api/user/credits sync.
      // Later JWT refreshes must not overwrite a fresher DB balance.
      if (!creditsSynced) {
        setCredits(session.user.credits ?? 0);
      }
    } else if (sessionStatus === 'unauthenticated') {
      setIsLoggedIn(false);
      setCredits(0);
      setCreditsSynced(false);
      setShowCreditsTopUpModal(false);
      creditsTopUpDismissedRef.current = false;
    }
  }, [sessionStatus, session?.user?.credits, creditsSynced]);

  // JWT can lag behind DB; sync credits once per login without session.update() (avoids /api/auth/session storms).
  useEffect(() => {
    if (sessionStatus !== 'authenticated') {
      creditsFetchedForAuthRef.current = false;
      return;
    }
    if (creditsFetchedForAuthRef.current) return;
    creditsFetchedForAuthRef.current = true;

    const controller = new AbortController();
    void fetch('/api/user/credits', { cache: 'no-store', signal: controller.signal })
      .then((res) => (res.ok ? res.json() : null))
      .then((data) => {
        if (typeof data?.credits === 'number') setCredits(data.credits);
      })
      .catch(() => {})
      .finally(() => {
        if (!controller.signal.aborted) setCreditsSynced(true);
      });

    return () => controller.abort();
  }, [sessionStatus]);

  const showCreditsExhausted =
    credits <= 0 && (activeTab === 'Task 1' || activeTab === 'Task 2');

  // Auto-open top-up packs once when credits hit zero on Task tabs (reopens after balance reloads > 0).
  useEffect(() => {
    if (credits > 0) {
      creditsTopUpDismissedRef.current = false;
      setShowCreditsTopUpModal(false);
      return;
    }
    if (
      sessionStatus === 'authenticated' &&
      creditsSynced &&
      showCreditsExhausted &&
      !creditsTopUpDismissedRef.current
    ) {
      setShowCreditsTopUpModal(true);
    }
  }, [credits, creditsSynced, sessionStatus, showCreditsExhausted]);

  useEffect(() => {
    preloadSpeechVoices();
  }, []);

  // Stuck spinner after network timeout or credits exhausted mid-request.
  useEffect(() => {
    if (credits > 0) return;
    setLoadingT1(false);
    setLoadingT2(false);
  }, [credits]);

  useEffect(() => {
    if (!scrollToScoreAfterAnalyzeRef.current) return;
    if (activeAnalyzeLoading || !activeResult) return;
    scrollToScoreAfterAnalyzeRef.current = false;
    if (typeof window === 'undefined') return;
    if (!window.matchMedia('(max-width: 1279px)').matches) return;
    window.setTimeout(() => {
      document.getElementById('stratum-results-score')?.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }, 150);
  }, [activeResult, activeAnalyzeLoading]);

  useEffect(() => {
    if (typeof window === 'undefined') return;
    const params = new URLSearchParams(window.location.search);
    if (params.get('error') !== 'OAuthAccountNotLinked') return;
    update().then(() => {
      router.replace('/', { scroll: false });
    });
  }, [update, router]);

  // After Lemon Squeezy redirect (?credits=success) refresh balance + fire purchase conversion.
  useEffect(() => {
    if (typeof window === 'undefined') return;
    const params = new URLSearchParams(window.location.search);
    if (params.get('credits') !== 'success') return;

    const packId = String(params.get('pack') || '').trim();
    const valueRaw = params.get('value');
    const value = valueRaw != null && valueRaw !== '' ? Number(valueRaw) : 0;

    trackGoogleAdsPurchaseConversion({
      value: Number.isFinite(value) ? value : 0,
      currency: 'USD',
      packId: packId || undefined,
      transactionId: packId ? `lemon_${packId}` : 'lemon_ok',
    });

    let cancelled = false;
    const refresh = async () => {
      try {
        const res = await fetch('/api/user/credits', { cache: 'no-store' });
        const data = await res.json().catch(() => ({}));
        if (!cancelled && typeof data?.credits === 'number') {
          setCredits(data.credits);
          setCreditsSynced(true);
        }
        await update();
      } catch {
        /* ignore */
      } finally {
        if (!cancelled) {
          router.replace('/?app=1', { scroll: false });
        }
      }
    };
    void refresh();
    return () => {
      cancelled = true;
    };
  }, [update, router]);

  useEffect(() => {
    setAppliedCorrections([]);
  }, [activeResult]);

  const { handleAnalyze } = useAnalyze({
    session,
    sessionStatus,
    credits,
    essayT1,
    essayT2,
    promptT1Academic,
    promptT1Letter,
    promptT2,
    task1Kind,
    letterMeta,
    image,
    setResultT1,
    setResultT2,
    setLoadingT1,
    setLoadingT2,
    setError,
    setErrorIs401,
    setIsAuthOpen,
    setAuthModalMessage,
    setCredits,
    scrollToScoreAfterAnalyzeRef,
    onCreditsExhausted: openCreditsTopUpModal,
  });

  const resetTask1 = () => {
    if (window.confirm('Delete all Task 1 data? Your essay, chart, and analysis will be lost.')) {
      setEssayT1('');
      setPromptT1Academic(DEFAULT_PROMPT_T1_ACADEMIC);
      setPromptT1Letter('');
      setTask1Kind('academic');
      setLetterMeta({ ...DEFAULT_LETTER_META });
      setResultT1(null);
      setTutorCommentT1('');
      setImage(null);
    }
  };

  const resetTask2 = () => {
    if (window.confirm('Delete all Task 2 data? Your essay, topic, and analysis will be lost.')) {
      setEssayT2('');
      setPromptT2('');
      setResultT2(null);
      setTutorCommentT2('');
      setIsAutoGenerated(false);
      setCurrentTopic(null);
    }
  };

  const downloadReport = async (archiveEntry = null) => {
    try {
      const entry =
        archiveEntry &&
        typeof archiveEntry === 'object' &&
        ('fullData' in archiveEntry || 'taskType' in archiveEntry)
          ? archiveEntry
          : null;
      const isT1 = entry ? entry.taskType === 'Task 1' : activeTab === 'Task 1';
      const result = entry ? entry.fullData : isT1 ? activeResultT1 : activeResultT2;
      const essayText = entry ? entry.essay : isT1 ? essayT1 : essayT2;
      const chartImage = entry ? entry.image : isT1 ? image : null;
      const promptText = entry ? entry.question || entry.prompt || '' : isT1 ? promptT1Active : promptT2;
      const tutorComment = entry
        ? entry.fullData?.tutor_comment || ''
        : isT1
          ? tutorCommentT1
          : tutorCommentT2;

      if (!result) return alert('Analysis data not found!');

      await generateStratumWritingPdf({
        isT1,
        result,
        essay: essayText,
        chartImage,
        promptText,
        task1Kind: result?.task1Kind || (isT1 ? task1Kind : 'academic'),
        tutorComment,
      });
    } catch (err) {
      console.error('PDF Error:', err);
      alert('Error generating PDF');
    }
  };

  const speak = (text) => {
    speakText(text, { lang: 'en-US', rate: 0.85 });
  };

  const currentWordCount = getEssayWordCount(activeTab === 'Task 1' ? essayT1 : essayT2);
  const targetWords = activeTab === 'Task 1' ? 150 : 250;

  /** Home CTA: open Task 2 editor ready to paste an essay for evaluation. */
  const goToEvaluateDraft = useCallback(() => {
    setActiveTab('Task 2');
    window.setTimeout(() => scrollToEditor({ focus: true }), 80);
  }, []);

  return {
    session,
    sessionStatus,
    forceLanding,
    skipAppLanding,
    isAuthOpen,
    setIsAuthOpen,
    authModalMessage,
    setAuthModalMessage,
    feedbackBanner: feedbackApi.feedbackBanner,
    setFeedbackBanner: feedbackApi.setFeedbackBanner,
    scrollToFeedbackForm: feedbackApi.scrollToFeedbackForm,
    activeTab,
    setActiveTab,
    isMenuOpen,
    setIsMenuOpen,
    isLoggedIn,
    setIsLoggedIn,
    credits,
    darkMode,
    scrollToEditor,
    goToEvaluateDraft,
    isGenLoadingT1: taskGen.isGenLoadingT1,
    generateTask1Data: taskGen.generateTask1Data,
    isGenLoadingLetter: taskGen.isGenLoadingLetter,
    generateLetterTask: taskGen.generateLetterTask,
    customKeyword,
    setCustomKeyword,
    setGenTopicError: taskGen.setGenTopicError,
    genTopicError: taskGen.genTopicError,
    genLoading: taskGen.genLoading,
    handleGenerateTask2: taskGen.handleGenerateTask2,
    task1Kind,
    setTask1Kind,
    setImageUploadError: taskGen.setImageUploadError,
    resetTask1,
    resetTask2,
    timeLeft: timer.timeLeft,
    timerActive: timer.timerActive,
    setTimerActive: timer.setTimerActive,
    isGtLetter,
    letterMeta,
    setLetterMeta,
    image,
    isDescribing: taskGen.isDescribing,
    imageUploadError: taskGen.imageUploadError,
    handleImageUpload: taskGen.handleImageUpload,
    currentTopic,
    isPromptOpen,
    setIsPromptOpen,
    promptT1Active,
    promptT2,
    setPromptT1Letter,
    setPromptT1Academic,
    setPromptT2,
    essayT1,
    essayT2,
    setEssayT1,
    setEssayT2,
    currentWordCount,
    targetWords,
    highlightRef: editorTools.highlightRef,
    editorRef: editorTools.editorRef,
    handleScroll: editorTools.handleScroll,
    renderColoredText: editorTools.renderColoredText,
    setIsFocused,
    playClickSound: editorTools.playClickSound,
    saveCurrentToArchive: archiveApi.saveCurrentToArchive,
    tutorCommentT1,
    tutorCommentT2,
    setTutorCommentT1,
    setTutorCommentT2,
    activeTutorComment: activeTab === 'Task 1' ? tutorCommentT1 : tutorCommentT2,
    setActiveTutorComment: activeTab === 'Task 1' ? setTutorCommentT1 : setTutorCommentT2,
    activeResult,
    isSaved,
    isSavingArchive: archiveApi.isSavingArchive,
    error,
    errorIs401,
    setError,
    setErrorIs401,
    handleAnalyze,
    loadingT1,
    loadingT2,
    activeResultsRef,
    downloadReport,
    shareReport: shareApi.shareReport,
    shareLoading: shareApi.shareLoading,
    handleCriteriaScoreChange: manualScoring.handleCriteriaScoreChange,
    handleResetToAiScores: manualScoring.handleResetToAiScores,
    activeResultT1,
    activeResultT2,
    activeAnalyzeLoading,
    appliedCorrections,
    handleReplaceWord: editorTools.handleReplaceWord,
    speak,
    triggerHighlight: editorTools.triggerHighlight,
    insertLinkingWord: editorTools.insertLinkingWord,
    searchState: editorTools.searchState,
    replaceNext: editorTools.replaceNext,
    mergedLexicalUpgrade,
    handleApplyAllUpgrades: editorTools.handleApplyAllUpgrades,
    showCreditsExhausted,
    showCreditsTopUpModal,
    openCreditsTopUpModal,
    closeCreditsTopUpModal,
    setShowSupportModal: feedbackApi.setShowSupportModal,
    karaokeAudio,
    archive: archiveApi.archive,
    clearArchive: archiveApi.clearArchive,
    handleDeleteArchiveEntry: archiveApi.handleDeleteArchiveEntry,
    handleReviewArchiveEntry: archiveApi.handleReviewArchiveEntry,
    handleSubmit: feedbackApi.handleSubmit,
    shareModal: shareApi.shareModal,
    setShareModal: shareApi.setShareModal,
    copyShareLink: shareApi.copyShareLink,
    nativeShareLink: shareApi.nativeShareLink,
    showSupportModal: feedbackApi.showSupportModal,
    supportFirstFieldRef: feedbackApi.supportFirstFieldRef,
    showScrollTop: scrollUi.showScrollTop,
    scrollProgress: scrollUi.scrollProgress,
    handleScrollToTop: scrollUi.handleScrollToTop,
  };
}
